/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrackOrderIdRouteImport } from './routes/track.$orderId'
import { Route as PaymentOrderIdRouteImport } from './routes/payment.$orderId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminMenusRouteImport } from './routes/admin.menus'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiPublicMidtransNotificationRouteImport } from './routes/api/public/midtrans-notification'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrackOrderIdRoute = TrackOrderIdRouteImport.update({
  id: '/track/$orderId',
  path: '/track/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentOrderIdRoute = PaymentOrderIdRouteImport.update({
  id: '/payment/$orderId',
  path: '/payment/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenusRoute = AdminMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicMidtransNotificationRoute =
  ApiPublicMidtransNotificationRouteImport.update({
    id: '/api/public/midtrans-notification',
    path: '/api/public/midtrans-notification',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/users': typeof AdminUsersRoute
  '/payment/$orderId': typeof PaymentOrderIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/midtrans-notification': typeof ApiPublicMidtransNotificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/users': typeof AdminUsersRoute
  '/payment/$orderId': typeof PaymentOrderIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/midtrans-notification': typeof ApiPublicMidtransNotificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/users': typeof AdminUsersRoute
  '/payment/$orderId': typeof PaymentOrderIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/midtrans-notification': typeof ApiPublicMidtransNotificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/admin/analytics'
    | '/admin/locations'
    | '/admin/menus'
    | '/admin/users'
    | '/payment/$orderId'
    | '/track/$orderId'
    | '/admin/'
    | '/api/public/midtrans-notification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/admin/analytics'
    | '/admin/locations'
    | '/admin/menus'
    | '/admin/users'
    | '/payment/$orderId'
    | '/track/$orderId'
    | '/admin'
    | '/api/public/midtrans-notification'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/admin/analytics'
    | '/admin/locations'
    | '/admin/menus'
    | '/admin/users'
    | '/payment/$orderId'
    | '/track/$orderId'
    | '/admin/'
    | '/api/public/midtrans-notification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  PaymentOrderIdRoute: typeof PaymentOrderIdRoute
  TrackOrderIdRoute: typeof TrackOrderIdRoute
  ApiPublicMidtransNotificationRoute: typeof ApiPublicMidtransNotificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/track/$orderId': {
      id: '/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/track/$orderId'
      preLoaderRoute: typeof TrackOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$orderId': {
      id: '/payment/$orderId'
      path: '/payment/$orderId'
      fullPath: '/payment/$orderId'
      preLoaderRoute: typeof PaymentOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menus': {
      id: '/admin/menus'
      path: '/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AdminMenusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/midtrans-notification': {
      id: '/api/public/midtrans-notification'
      path: '/api/public/midtrans-notification'
      fullPath: '/api/public/midtrans-notification'
      preLoaderRoute: typeof ApiPublicMidtransNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminMenusRoute: typeof AdminMenusRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminMenusRoute: AdminMenusRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  PaymentOrderIdRoute: PaymentOrderIdRoute,
  TrackOrderIdRoute: TrackOrderIdRoute,
  ApiPublicMidtransNotificationRoute: ApiPublicMidtransNotificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
